train_dataset:
  dataset:
    name: realsrarbi-image-folders
    args:
      root_path_hr1dot5: ./load/Train/HR1dot5
      root_path_lr1dot5: ./load/Train/LR1dot5
      root_path_hr2: ./load/Train/HR2
      root_path_lr2: ./load/Train/LR2
      root_path_hr2dot5: ./load/Train/HR2dot5
      root_path_lr2dot5: ./load/Train/LR2dot5
      root_path_hr3: ./load/Train/HR3
      root_path_lr3: ./load/Train/LR3
      root_path_hr3dot5: ./load/Train/HR3dot5
      root_path_lr3dot5: ./load/Train/LR3dot5
      root_path_hr4: ./load/Train/HR4
      root_path_lr4: ./load/Train/LR4
      repeat: 20
      cache: in_memory
  wrapper:
    name: realsrarbi-deform-paired
    args:
      inp_size: 48
      scale_min: 1.5
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: realsrarbi-image-folders
    args:
      root_path_hr2: ./load/Test/HR2
      root_path_lr2: ./load/Test/LR2
      root_path_hr3: ./load/Test/HR3
      root_path_lr3: ./load/Test/LR3
      root_path_hr4: ./load/Test/HR4
      root_path_lr4: ./load/Test/LR4
      root_path_hr1dot5: ./load/Test/HR1dot5
      root_path_lr1dot5: ./load/Test/LR1dot5
      root_path_hr2dot5: ./load/Test/HR2dot5
      root_path_lr2dot5: ./load/Test/LR2dot5
      root_path_hr3dot5: ./load/Test/HR3dot5
      root_path_lr3dot5: ./load/Test/LR3dot5
      first_k: 10
      repeat: 160
#      cache: in_memory
      cache: none
  wrapper:
    name: realsrarbi-deform-paired
    args:
      inp_size: 48
      scale_min: 1.5
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}
  diff_rgb: {sub: [0.5], div: [0.5]}

model:
  name: liif-globaldeform
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    deformencoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [256, 256, 256, 256]
    deformnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list: [ 256, 256, 256, 256 ]

optimizer:
  name: adam
  args:
    lr: 2.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 10000
epoch_save: 100
